all:
  children:
    hypervisors:
      hosts:
        big0:
          ansible_host: "{{ fedora_host_ip }}"
          ansible_user: "{{ ansible_deploy_user | default('admin') }}"

    k8s_control_plane:
      hosts:
        k8s-control-01:
          ansible_host: "{{ k8s_control_01_ip }}"
          ansible_user: "{{ ansible_deploy_user | default('admin') }}"

    k8s_workers:
      hosts:
        k8s-worker-01:
          ansible_host: "{{ k8s_worker_01_ip }}"
          ansible_user: "{{ ansible_deploy_user | default('admin') }}"

    bastions:
      hosts:
        bastion-01:
          ansible_host: "{{ bastion_01_ip }}"
          ansible_user: "{{ ansible_deploy_user | default('admin') }}"

    guests:
      children:
        k8s_control_plane:
        k8s_workers:
        bastions:

    edge_nodes:
      hosts:
        littlehamster:
          ansible_user: "{{ ansible_deploy_user | default('admin') }}"
