all:
  children:
    hypervisors:
      hosts:
        fedora-host:
          ansible_host: "{{ fedora_host_ip }}"
          ansible_user: "{{ ansible_deploy_user | default('admin') }}"

    guests:
      hosts:
        rocky-wg:
          ansible_host: "{{ rocky_guest_ip }}"
          ansible_user: "{{ ansible_deploy_user | default('admin') }}"
